"""Generate all paper LaTeX tables directly from evaluation/v2_metrics/*.json.

No number in the paper is hand-typed: each table body is written to
research/paper/icassp2027/tables/*.tex and \\input by paper.tex. Re-run after
any eval refresh; the .tex files regenerate from whatever JSONs are present.

Usage:
  python research/paper/icassp2027/make_tables.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
M = os.path.join(REPO, "evaluation", "v2_metrics")
OUT = os.path.join(HERE, "tables")
os.makedirs(OUT, exist_ok=True)


def load(name):
    p = os.path.join(M, name)
    return json.load(open(p)) if os.path.exists(p) else None


def mix(name, key, src="all"):
    """A metric from a *_mixing.json ('all' source), or None if absent."""
    d = load(f"{name}_mixing.json")
    if not d:
        return None
    return d["metrics"].get(key, {}).get(src)


def fad(name):
    d = load(f"{name}_fad.json")
    if not d:
        return None
    return d.get("fad/all") or d.get("metrics", {}).get("fad", {}).get("all")


def sub(name, stem="all", field="sdr_sub"):
    d = load(f"{name}_subtraction.json")
    if not d:
        return None
    return d["subtraction"].get(stem, {}).get(field)


def f(x, nd=2, plus=False):
    """Format a number or '--' if missing."""
    if x is None:
        return "--"
    s = f"{x:+.{nd}f}" if plus else f"{x:.{nd}f}"
    return s


def write(fname, body):
    path = os.path.join(OUT, fname)
    with open(path, "w") as fh:
        fh.write(body)
    print(f"wrote {os.path.relpath(path, REPO)}")


# ---------------------------------------------------------------------------
# Table 1 — v2 mechanism ablation (the headline ablation on the GAN AE).
# Columns: SDR_rec, SDR_lin (decode-vs-decode), SDR_lin_gt (vs GT), l_lat, MixRate.
def table_ablation():
    rows = [
        ("v2.0-continued",        "baseline (no mix)"),
        ("v2.1-decmix",           "$\\mathcal{L}_\\mathrm{dec}$"),
        ("v2.2-decmix-disc",      "$\\mathcal{L}_\\mathrm{dec}$ + disc-on-mix"),
        ("v2.3-encmix-g5",        "$\\mathcal{L}_\\mathrm{enc}$ ($\\gamma{=}5$)"),
        ("v2.4-encmix-g10",       "$\\mathcal{L}_\\mathrm{enc}$ ($\\gamma{=}10$)"),
        ("v2.5-encmix-g20",       "$\\mathcal{L}_\\mathrm{enc}$ ($\\gamma{=}20$)"),
        ("v2.6-decmix-frozenenc", "$\\mathcal{L}_\\mathrm{dec}$ frozen-enc"),
    ]
    lines = []
    for name, label in rows:
        lines.append(
            f"    {label} & {f(mix(name,'sdr_rec'),1,1)} & "
            f"{f(mix(name,'sdr_lin'),1,1)} & {f(mix(name,'sdr_lin_gt'),1,1)} & "
            f"{f(mix(name,'l_lat'),3)} & {f(mix(name,'mix_rate'),3)} \\\\")
    body = (
        "% AUTO-GENERATED by make_tables.py — do not edit by hand (regenerate via make_tables.py).\n"
        "\\begin{tabular}{@{}lccccc@{}}\n\\toprule\n"
        "Loss & SDR$_\\mathrm{rec}$ & SDR$_\\mathrm{lin}$ & "
        "SDR$_\\mathrm{lin}^\\mathrm{gt}$ & $\\ell_\\mathrm{lat}$ & MixRate \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")
    write("ablation.tex", body)


# ---------------------------------------------------------------------------
# Table 2 — cross-architecture / M2L (EMA-consistent) + v3 from-scratch.
def table_crossarch():
    rows = [
        ("v2.0-continued",       "GAN AE, 7.66$\\times$, no mix",  "mix", None),
        ("v2.1-decmix",          "GAN AE, 7.66$\\times$, +mix",    "mix", None),
        ("v3.0-baseline-d64",    "GAN AE, 15.3$\\times$, no mix",  "mix", None),
        ("v3.1-decmix-disc-d64", "GAN AE, 15.3$\\times$, +mix",    "mix", None),
        ("m2l_phase0_ema",       "M2L, no mix (baseline)",         "m2l", "fad0"),
        ("m2l_phase05_ema",      "M2L, fine-tune control",         "m2l", None),
        ("m2l_phase2_ema",       "M2L, +mix",                      "m2l", None),
    ]
    lines = []
    for name, label, kind, flag in rows:
        fad_name = "m2l_phase0_fad.json" if flag == "fad0" else f"{name}_fad.json"
        fd = load(fad_name)
        fadv = (fd.get("fad/all") if fd else None)
        lines.append(
            f"    {label} & {f(mix(name,'sdr_rec'),1,1)} & "
            f"{f(mix(name,'sdr_lin'),1,1)} & {f(mix(name,'sdr_lin_gt'),1,1)} & "
            f"{f(mix(name,'mix_rate'),3)} & {f(fadv,3)} \\\\")
    body = (
        "% AUTO-GENERATED by make_tables.py — do not edit by hand (regenerate via make_tables.py).\n"
        "\\begin{tabular}{@{}lccccc@{}}\n\\toprule\n"
        "Model & SDR$_\\mathrm{rec}$ & SDR$_\\mathrm{lin}$ & "
        "SDR$_\\mathrm{lin}^\\mathrm{gt}$ & MixRate & FAD \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")
    write("crossarch.tex", body)


# ---------------------------------------------------------------------------
# Table 3 — downstream stem-removal subtraction (per stem, GAN models + M2L).
def table_subtraction():
    rows = [
        ("v2.0-continued",         "v2.0 no-mix"),
        ("v2.1-decmix",            "v2.1 +mix"),
        ("v2.2-decmix-disc",       "v2.2 +mix+disc"),
        ("v3.1-decmix-disc-d64",   "v3.1 +mix (15.3$\\times$)"),
        ("m2l_phase2_ema",         "M2L +mix"),
    ]
    stems = ["drums", "bass", "vocals", "other", "all"]
    lines = []
    for name, label in rows:
        cells = " & ".join(f(sub(name, st), 1, 1) for st in stems)
        lines.append(f"    {label} & {cells} \\\\")
    body = (
        "% AUTO-GENERATED by make_tables.py — do not edit by hand (regenerate via make_tables.py).\n"
        "\\begin{tabular}{@{}lccccc@{}}\n\\toprule\n"
        "Model & drums & bass & vocals & other & all \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")
    write("subtraction.tex", body)


if __name__ == "__main__":
    table_ablation()
    table_crossarch()
    table_subtraction()
    print("\nNote: '--' cells mean the source JSON is missing or lacks the "
          "metric (e.g. v3.1 sdr_lin_gt before the re-eval lands).")
